<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <RootNamespace>Shotx</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../packages/shotx-unity/Runtime/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SocketIOClient" Version="3.1.2" />
    <PackageReference Include="SocketIO.Serializer.NewtonsoftJson" Version="3.1.2" />
  </ItemGroup>

</Project>
